f = open("b.txt", "w")
f.write(";Mapa hecho por Ian Sanna")
f.write("\n")
f.write(";Los elementos en el mapa corresponden de la siguiente manera")
f.write("\n")
f.write(";  X: Valle")
f.write("\n")
f.write(";  Y: Montaña")
f.write("\n")
f.write(";  M: Mar")
f.write("\n")
f.write("\n")
f.write("; Empezando el nivel:")